### ISSUE TITLE
branch 1.09_oyo_add_an_edit_time_field_using_servervalue.timestamp | timestampLastChanged: null

### ISSUE THREAD

**Issue by JGeovani** [udacity/ShoppingListPlusPlus#1]
I got NullPointerException when running the app in the branch 1.09_oyo_add_an_edit_time_field_using_servervalue.timestamp

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
                                                                                               at com.udacity.firebase.shoppinglistplusplus.model.ShoppingList.getTimestampLastChangedLong(ShoppingList.java:58)

**Comment by ceruleanotter** [comment]
Thanks for pointing this out - the issue is likely that you're giving it old data without a timestampLastChanged; when you read in the data, the timestampLastChanged map is null, which creates problems when you try to extract a long value from it. If you clear the database of data from the last step, it should run without issue.

Also, adding something like the code below is one way to fix the issue (that, or a check in the .getTimestampLastChangedLong method):

<pre>
                    if (shoppingList.getTimestampLastChanged() != null) {
                        mTextViewEditTime.setText(
                                Utils.SIMPLE_DATE_FORMAT.format(
                                        new Date(shoppingList.getTimestampLastChangedLong())));
                    } else {
                        mTextViewEditTime.setText("");
                    }
</pre>

I'll keep this open and add some code to check for null the next time we update the repo.

**Comment by ceruleanotter** [comment]
This has been fixed and the fix will be pushed during the lesson 4/5 update.
